In [1]:
import numpy as np
import time

# Vectorizing

In [2]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)

## 벡터화 버전

In [3]:
tic=time.time()
c=np.dot(a,b)
toc=time.time()

In [4]:
print(c)
print('벡터화 버전:',str(1000*(toc-tic))+'ms')

249995.69292419736
벡터화 버전: 34.99937057495117ms


## 비벡터화 버전

In [5]:
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

In [6]:
print(c)
print('for loop 버전:',str(1000*(toc-tic))+'ms')

249995.69292419063
for loop 버전: 488.76142501831055ms


# Broadcasting in Python

In [3]:
import numpy as np

In [4]:
A= np.array([ [56.0, 0.0, 4.4, 68.0],
[1.2, 104.0, 52.0, 8.0,],
[1.8, 135.0, 99.0, 0.9]])

In [5]:
cal=A.sum(axis=0) #axis=0: 수직으로 합산 axis=1이면 수평으로 합산

In [6]:
percentage=A/cal.reshape(1,4)*100 
# cal의 shape 모르는 경우가 있기에 reshape를 넣어주는 것을 추천한다.

In [7]:
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

# 파이썬/Numpy 팁

버그를 줄이는 코딩 팁을 이야기한다.

In [17]:
a=np.random.rand(5)
print(a)
print(a.shape) #여기서 A는 행켁터도, 열백터도 아님

[0.41318586 0.98703847 0.74350874 0.97561573 0.31432908]
(5,)


In [15]:
print(a.T) #a와 a 전치 값이 동일하다

[0.70493951 0.62534289 0.4463525  0.27157807 0.49613265]


In [18]:
print(np.dot(a,a.T)) 
# a와 a전치를 외적할경우에 행렬이 반환되어야 하지만 값 1개만 리턴된다.

2.7484015758178737


#### 따라서 위에처럼 생성하는 것이 아니라 n,1로 생성할것!!\
위에처럼 생성할 경우 행벡터나 열벡터로 일정하게 동작하지 않는다.

In [19]:
a=np.random.rand(5,1) #요렇게 열벡터 생성
print(a)

[[0.29872288]
 [0.16173437]
 [0.93002407]
 [0.77120114]
 [0.98276693]]


In [20]:
print(a.T) #a와 a 전치 값이 다르다 전치는 행벡터

[[0.29872288 0.16173437 0.93002407 0.77120114 0.98276693]]


In [21]:
print(np.dot(a,a.T)) # 여기서는 정상적으로 외적되어 행렬이 리턴된다.

[[0.08923536 0.04831376 0.27781947 0.23037543 0.29357497]
 [0.04831376 0.02615801 0.15041685 0.12472973 0.15894719]
 [0.27781947 0.15041685 0.86494476 0.71723562 0.9139969 ]
 [0.23037543 0.12472973 0.71723562 0.5947512  0.75791098]
 [0.29357497 0.15894719 0.9139969  0.75791098 0.96583084]]


### assert로 에러 처리를 만들어라
벡터의 차원이 정확하지 않을 때 사용하는 방법

In [22]:
assert (a.shape==(5,1)) #a의 모양이 5X1인지 확실히 한다.

#### np.random.rand(5)을 rank 1 array라고 하는데 이를 사용하지 말것!!
이를 사용하였을 경우에는 reshape로 변형해라